#!/usr/bin/env node
// scripts/setup.mjs — idempotent install of tq as a launchd user agent.
// Node built-ins only; no npm dependencies.
import { execSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync, chmodSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { homedir } from "node:os";
import { createInterface } from "node:readline";

// ---------------------------------------------------------------------------
// Resolve paths
// ---------------------------------------------------------------------------
const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = dirname(scriptDir); // scripts/ is one level below root

function expandHome(p) {
  if (p === "~") return homedir();
  if (p.startsWith("~/")) return join(homedir(), p.slice(2));
  return p;
}

const HOME = homedir();
const dataRoot = process.env.TQ_DATA
  ? expandHome(process.env.TQ_DATA)
  : join(repoRoot, "data");
const configDir = join(repoRoot, "config");
const plistPath = join(HOME, "Library", "LaunchAgents", "tq.daemon.plist");
const shimPath = join(HOME, ".local", "bin", "task");
const label = "tq.daemon";

// ---------------------------------------------------------------------------
// Confirmation guard — require explicit yes when not installing to ~/.tq
// ---------------------------------------------------------------------------
const expectedRoot = join(HOME, ".tq");
const args = process.argv.slice(2);
const forceYes = process.env.FORCE === "1" || args.includes("--yes");

console.log("");
console.log("tq install — setup summary");
console.log("  repoRoot  :", repoRoot);
console.log("  dataRoot  :", dataRoot);
console.log("  configDir :", configDir);
console.log("  plist     :", plistPath);
console.log("  shim      :", shimPath);
console.log("  label     :", label);
console.log("");

if (repoRoot !== expectedRoot && !forceYes) {
  // Prompt for confirmation when running from a non-standard location
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const confirmed = await new Promise((resolve) => {
    rl.question(
      `Repo root is not ~/.tq (it is ${repoRoot}).\nContinue anyway? [y/N] `,
      (ans) => {
        rl.close();
        resolve(ans.trim().toLowerCase() === "y");
      },
    );
  });
  if (!confirmed) {
    console.log("Aborted.");
    process.exit(1);
  }
}

// ---------------------------------------------------------------------------
// 1. Create directories
// ---------------------------------------------------------------------------
mkdirSync(configDir, { recursive: true });
mkdirSync(join(dataRoot, "run"), { recursive: true });
mkdirSync(join(dataRoot, "attachments"), { recursive: true });
console.log("✓ directories created");

// ---------------------------------------------------------------------------
// 2. Seed config.toml from example (never overwrite)
// ---------------------------------------------------------------------------
const configToml = join(configDir, "config.toml");
if (!existsSync(configToml)) {
  copyFileSync(join(repoRoot, "config.example.toml"), configToml);
  console.log("✓ config.toml seeded from config.example.toml");
} else {
  console.log("· config.toml already exists — not overwritten");
}

// ---------------------------------------------------------------------------
// 3. Seed tq.env secrets template (never overwrite)
// ---------------------------------------------------------------------------
const envFile = join(configDir, "tq.env");
if (!existsSync(envFile)) {
  const template = [
    "# tq secrets — loaded by the daemon at startup.",
    "# Real environment variables always take precedence over values here.",
    "# chmod 0600 is set automatically; never commit this file.",
    "#",
    "# ATLASSIAN_EMAIL=you@example.com",
    "# ATLASSIAN_API_TOKEN=your_atlassian_api_token",
    "# GITHUB_TOKEN=your_github_token",
    "# AWS_PROFILE=your_aws_profile",
    "",
  ].join("\n");
  writeFileSync(envFile, template, { mode: 0o600 });
  console.log("✓ tq.env template written (chmod 0600)");
} else {
  console.log("· tq.env already exists — not overwritten");
}

// ---------------------------------------------------------------------------
// 4. Install global `task` shim at ~/.local/bin/task
// ---------------------------------------------------------------------------
mkdirSync(join(HOME, ".local", "bin"), { recursive: true });
const tsxBin = join(repoRoot, "node_modules", ".bin", "tsx");
const cliEntry = join(repoRoot, "packages", "cli", "src", "index.ts");
const shimContent = [
  "#!/usr/bin/env bash",
  `# Auto-generated by tq setup.mjs — do not edit by hand.`,
  `exec "${tsxBin}" "${cliEntry}" "$@"`,
  "",
].join("\n");
writeFileSync(shimPath, shimContent);
chmodSync(shimPath, 0o755);
console.log("✓ task shim installed at", shimPath);

// Check if ~/.local/bin is on PATH
const pathDirs = (process.env.PATH ?? "").split(":");
const localBin = join(HOME, ".local", "bin");
if (!pathDirs.includes(localBin)) {
  console.log("");
  console.log("⚠  ~/.local/bin is not on your PATH. Add this to your shell profile:");
  console.log(`   export PATH="${localBin}:$PATH"`);
}

// ---------------------------------------------------------------------------
// 5. Generate launchd plist (no EnvironmentVariables in plist — use tq.env)
// ---------------------------------------------------------------------------
const nodeExec = process.execPath; // path to the node binary running this script
const daemonMain = join(repoRoot, "packages", "daemon", "src", "main.ts");
const stdoutLog = join(dataRoot, "run", "daemon.log");
const stderrLog = join(dataRoot, "run", "daemon.err");

const plistContent = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${nodeExec}</string>
    <string>${tsxBin}</string>
    <string>${daemonMain}</string>
  </array>
  <key>WorkingDirectory</key><string>${repoRoot}</string>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>${stdoutLog}</string>
  <key>StandardErrorPath</key><string>${stderrLog}</string>
</dict>
</plist>
`;

mkdirSync(dirname(plistPath), { recursive: true });
writeFileSync(plistPath, plistContent);
console.log("✓ plist written to", plistPath);

// ---------------------------------------------------------------------------
// 6. Load the launchd agent
// ---------------------------------------------------------------------------
const uid = process.getuid();
const guiTarget = `gui/${uid}/${label}`;
const guiDomain = `gui/${uid}`;

try {
  // Unload any existing instance (ignore failure — it may not be loaded yet)
  execSync(`launchctl bootout ${guiTarget} 2>/dev/null || true`, { stdio: "inherit" });
} catch {
  // Ignore
}

let loaded = false;
try {
  execSync(`launchctl bootstrap ${guiDomain} "${plistPath}"`, { stdio: "inherit" });
  loaded = true;
} catch {
  // Fall back to legacy unload/load for older macOS
  try {
    execSync(`launchctl unload "${plistPath}" 2>/dev/null || true`, { stdio: "inherit" });
    execSync(`launchctl load "${plistPath}"`, { stdio: "inherit" });
    loaded = true;
  } catch (e) {
    console.error("⚠  launchctl load failed:", e.message);
  }
}

if (loaded) {
  console.log("✓ launchd agent loaded:", label);
}

// ---------------------------------------------------------------------------
// 7. Health check
// ---------------------------------------------------------------------------
console.log("\nWaiting for daemon to start…");
await new Promise((r) => setTimeout(r, 1200));

try {
  const res = await fetch("http://127.0.0.1:7788/api/health");
  if (res.ok) {
    console.log("✓ daemon health OK (http://127.0.0.1:7788)");
  } else {
    console.log("❌ daemon returned HTTP", res.status);
  }
} catch {
  console.log("❌ daemon not reachable at http://127.0.0.1:7788/api/health (may still be starting)");
}

// ---------------------------------------------------------------------------
// 8. Summary
// ---------------------------------------------------------------------------
console.log("\n── tq install complete ──────────────────────────────────────");
console.log("  config  :", configToml);
console.log("  secrets :", envFile);
console.log("  data    :", dataRoot);
console.log("  logs    :", stdoutLog);
console.log("  shim    :", shimPath);
console.log("  plist   :", plistPath);
console.log("");
console.log("Edit", envFile, "to add AWS/Atlassian/GitHub credentials.");
console.log("Run `make update` after `git pull` to rebuild and restart the daemon.");
